//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0-b170531.0717 
//         See <a href="https://jaxb.java.net/">https://jaxb.java.net/</a> 
//         Any modifications to this file will be lost upon recompilation of the source schema. 
//         Generated on: 2017.12.09 at 11:33:55 AM MSK 
//


package d.java.task03xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected         content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="guns" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="Handy"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte"&gt;
 *                         &lt;minInclusive value="1"/&gt;
 *                         &lt;maxInclusive value="2"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Origin"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="RU"/&gt;
 *                         &lt;enumeration value="EU"/&gt;
 *                         &lt;enumeration value="UK"/&gt;
 *                         &lt;enumeration value="US"/&gt;
 *                         &lt;enumeration value="AFR"/&gt;
 *                         &lt;enumeration value="CH"/&gt;
 *                         &lt;enumeration value="JP"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="TTC"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                             &lt;element name="sighting_rang" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
 *                             &lt;element name="collar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="optic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="Material"&gt;
 *                     &lt;simpleType&gt;
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                         &lt;enumeration value="stal"/&gt;
 *                         &lt;enumeration value="plastik"/&gt;
 *                         &lt;enumeration value="splav"/&gt;
 *                       &lt;/restriction&gt;
 *                     &lt;/simpleType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *                 &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "guns"
})
@XmlRootElement(name = "Gun")
public class Gun {

    protected List<Gun.Guns> guns;

    /**
     * Gets the value of the guns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGuns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gun.Guns }
     * 
     * 
     */
    public List<Gun.Guns> getGuns() {
        if (guns == null) {
            guns = new ArrayList<Gun.Guns>();
        }
        return this.guns;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected         content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="Model" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="Handy"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}byte"&gt;
     *               &lt;minInclusive value="1"/&gt;
     *               &lt;maxInclusive value="2"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Origin"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="RU"/&gt;
     *               &lt;enumeration value="EU"/&gt;
     *               &lt;enumeration value="UK"/&gt;
     *               &lt;enumeration value="US"/&gt;
     *               &lt;enumeration value="AFR"/&gt;
     *               &lt;enumeration value="CH"/&gt;
     *               &lt;enumeration value="JP"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="TTC"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *                   &lt;element name="sighting_rang" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
     *                   &lt;element name="collar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="optic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="Material"&gt;
     *           &lt;simpleType&gt;
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *               &lt;enumeration value="stal"/&gt;
     *               &lt;enumeration value="plastik"/&gt;
     *               &lt;enumeration value="splav"/&gt;
     *             &lt;/restriction&gt;
     *           &lt;/simpleType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}byte" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "model",
        "handy",
        "origin",
        "ttc",
        "material"
    })
    public static class Guns {

        @XmlElement(name = "Model", required = true)
        protected String model;
        @XmlElement(name = "Handy")
        protected byte handy;
        @XmlElement(name = "Origin", required = true)
        protected String origin;
        @XmlElement(name = "TTC", required = true)
        protected Gun.Guns.TTC ttc;
        @XmlElement(name = "Material", required = true)
        protected String material;
        @XmlAttribute(name = "id", required = true)
        protected byte id;

        /**
         * Gets the value of the model property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getModel() {
            return model;
        }

        /**
         * Sets the value of the model property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setModel(String value) {
            this.model = value;
        }

        /**
         * Gets the value of the handy property.
         * 
         */
        public byte getHandy() {
            return handy;
        }

        /**
         * Sets the value of the handy property.
         * 
         */
        public void setHandy(byte value) {
            this.handy = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

        /**
         * Gets the value of the ttc property.
         * 
         * @return
         *     possible object is
         *     {@link Gun.Guns.TTC }
         *     
         */
        public Gun.Guns.TTC getTTC() {
            return ttc;
        }

        /**
         * Sets the value of the ttc property.
         * 
         * @param value
         *     allowed object is
         *     {@link Gun.Guns.TTC }
         *     
         */
        public void setTTC(Gun.Guns.TTC value) {
            this.ttc = value;
        }

        /**
         * Gets the value of the material property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaterial() {
            return material;
        }

        /**
         * Sets the value of the material property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaterial(String value) {
            this.material = value;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public byte getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(byte value) {
            this.id = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected         content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="range" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
         *         &lt;element name="sighting_rang" type="{http://www.w3.org/2001/XMLSchema}short"/&gt;
         *         &lt;element name="collar" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="optic" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "range",
            "sightingRang",
            "collar",
            "optic"
        })
        public static class TTC {

            protected short range;
            @XmlElement(name = "sighting_rang")
            protected short sightingRang;
            @XmlElement(required = true)
            protected String collar;
            @XmlElement(required = true)
            protected String optic;

            /**
             * Gets the value of the range property.
             * 
             */
            public short getRange() {
                return range;
            }

            /**
             * Sets the value of the range property.
             * 
             */
            public void setRange(short value) {
                this.range = value;
            }

            /**
             * Gets the value of the sightingRang property.
             * 
             */
            public short getSightingRang() {
                return sightingRang;
            }

            /**
             * Sets the value of the sightingRang property.
             * 
             */
            public void setSightingRang(short value) {
                this.sightingRang = value;
            }

            /**
             * Gets the value of the collar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCollar() {
                return collar;
            }

            /**
             * Sets the value of the collar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCollar(String value) {
                this.collar = value;
            }

            /**
             * Gets the value of the optic property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOptic() {
                return optic;
            }

            /**
             * Sets the value of the optic property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOptic(String value) {
                this.optic = value;
            }

        }

    }

}
